FROM node:fermium-buster as node_builder
WORKDIR /var/src

ARG REACT_APP_API_ROOT

COPY package.json .
COPY yarn.lock .
RUN yarn 

COPY tsconfig.json .
COPY .eslintrc.yml .
COPY public/ ./public
COPY src/ ./src

RUN yarn build

FROM nginx:1.20

COPY --from=node_builder /var/src/build /var/www/
RUN rm /etc/nginx/nginx.conf
RUN rm -rf /etc/nginx/conf.d
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/conf.d/ /etc/nginx/conf.d

CMD ["nginx", "-g", "daemon off;"]
