apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: setup
          image: <image tag>
          envFrom:
            - secretRef: 
                name: postgres-secret
